// apps/card-web-components/src/main.tsx
// import { StrictMode } from 'react';
// import * as ReactDOM from 'react-dom/client';
// import App from './app/app';

// const root = ReactDOM.createRoot(
//   document.getElementById('root') as HTMLElement,
// );

// root.render(
//   <StrictMode>
//     <App />
//   </StrictMode>,
// );

import { ProductCard } from "./custom-elements/product-card";

if (!customElements.get('product-card')) {
  customElements.define(
    'product-card',
    ProductCard,
  );
}

// apps/card-component-demo/src/main.tsx
import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';
import App from './app/app';
import { Navigate, RouterProvider, createBrowserRouter } from 'react-router-dom';
import { productRouter } from '@card-component-demo/products-feature';
import 'unfonts.css';
import { QueryClientProvider } from '@tanstack/react-query';
import { QueryClient } from '@tanstack/react-query';

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: false,
      staleTime: 300000, // 5 minutes
    },
  },
});

const router = createBrowserRouter([
  {
    path: '/',
    element: <App />,
    children: [
      { index: true, element: <Navigate to="/products" replace /> },
      ...productRouter,
    ],
  },
]);

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement,
);

root.render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
